export interface IRepublic {
  respublicId: number,
  name: string,
  search_detail: ISearch,
  type: string,
  regions: regions[]
}
export interface ISearch {
  osmtype: string,
  osmid: number,
  coordinates: { lat: number, lon: number, zoom: number }
}
export interface regions {
  regionId: number,
  name: string,
  type: string,
  region_osm_id: number,
  neighborhood: string[] | INeighborhood[]
}
export interface INeighborhood { id: string, type: string, region_name: string }
export const republic: IRepublic[] = [
  {
    respublicId: 60,
    search_detail: {
      osmtype: 'R',
      osmid: 178016,
      coordinates: {
        lon: 72.5355339,
        lat: 40.7740809,
        zoom: 9,
      },
    },
    name: "Andijan",
    type: "region",
    regions: [
      {
        regionId: 1,
        name: "Andijon",
        type: "city",
        neighborhood: [],
        region_osm_id: 331189322,
      },
      {
        regionId: 2,
        name: "Andijon",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372690,
      },
      {
        regionId: 3,
        name: "Asaka",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372853,
      },
      {
        regionId: 4,
        name: "Jalaquduk",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372807,
      },
      {
        regionId: 5,
        name: "Qurghontepa",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372765,
      },
      {
        regionId: 6,
        name: "Marhamat",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372874,
      },
      {
        regionId: 7,
        name: "Izboskan",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372724,
      },
      {
        regionId: 8,
        name: "Pakhtaobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372718,
      },
      {
        regionId: 9,
        name: "Xodjaobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372664,
      },
      {
        regionId: 10,
        name: "Shahrikhon",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372736,
      },
      {
        regionId: 11,
        name: "Oltinkul",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372697,
      },
      {
        regionId: 12,
        name: "Baliqchi",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372808,
      },
      {
        regionId: 13,
        name: "ulug'nor", //check again
        type: "district",
        neighborhood: [],
        region_osm_id: 309372682,
      },
      {
        regionId: 14,
        name: "Bo'zton",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372682,
      },
      {
        regionId: 15,
        name: "Bulak bashi",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372697,
      },
      {
        regionId: 16,
        name: "Khonobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372697,
      }
    ]
  },
  {
    respublicId: 50,
    name: "Namangan",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 178017,
      coordinates: {
        lat: 40.9555061,
        lon: 71.1097749,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Namangan",
        type: "city",
        neighborhood: [],
        region_osm_id: 14348868,
      },
      {
        regionId: 2,
        name: "Kosonsoy",
        type: "district",
        neighborhood: [],
        region_osm_id: 27303193,
      },
      {
        regionId: 3,
        name: "Mingbuloq",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372817,
      },
      {
        regionId: 4,
        name: "Namangan",
        type: "district",
        neighborhood: [],
        region_osm_id: 245554769,
      },
      {
        regionId: 5,
        name: "Norin",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372744,
      },
      {
        regionId: 6,
        name: "Pop",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372697,
      },
      {
        regionId: 7,
        name: "Toʻraqoʻrgʻon",
        type: "district",
        neighborhood: [],
        region_osm_id: 187154935,
      },
      {
        regionId: 8,
        name: "Uychi",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372899,
      },
      {
        regionId: 9,
        name: "Uchqorghon",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372766,
      },
      {
        regionId: 10,
        name: "Chortoq",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372687,
      },
      {
        regionId: 11,
        name: "Chust",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372785,
      },
      {
        regionId: 12,
        name: "Yangiqorghon",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372902,
      },
    ]
  },
  {
    respublicId: 40,
    name: "Fergana",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 178018,
      coordinates: {
        lon: 71.25,
        lat: 40.5,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Fergana",
        type: "city",
        neighborhood: [],
        region_osm_id: 27143452,
      },
      {
        regionId: 2,
        name: "Farghona",
        type: "district",
        neighborhood: [
          {
            id: '2-1',
            region_name: 'fargona',
            type: 'airport'
          },
          {
            id: '2-2',
            region_name: "yangi-margilon",
            type: 'qishloq'
          }
        ],
        region_osm_id: 309372686,
      },
      {
        regionId: 3,
        name: "Oltiariq",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372790,
      },
      {
        regionId: 4,
        name: "Bagdad",
        type: "district",
        neighborhood: [],
        region_osm_id: 295885865,
      },
      {
        regionId: 5,
        name: "Beshariq",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372791,
      },
      {
        regionId: 6,
        name: "Buvayda",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372711,
      },
      {
        regionId: 7,
        name: "Danghara",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372679,
      },
      {
        regionId: 8,
        name: "Furqat",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372710,
      },
      {
        regionId: 9,
        name: "Qoshtepa",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372737,
      },
      {
        regionId: 10,
        name: "Quwa",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372693,
      },
      {
        regionId: 11,
        name: "Kuvasai",
        type: "district",
        neighborhood: [],
        region_osm_id: 169519815,
      },
      {
        regionId: 12,
        name: "Rishton",
        type: "district",
        neighborhood: [],
        region_osm_id: 246212873,
      },
      {
        regionId: 13,
        name: "Soʻx",
        type: "district",
        neighborhood: [],
        region_osm_id: 3772474,
      },
      {
        regionId: 14,
        name: "Toshloq",
        type: "district",
        neighborhood: [],
        region_osm_id: 247137853,
      },
      {
        regionId: 15,
        name: "Uchkoʻprik",
        type: "district",
        neighborhood: [],
        region_osm_id: 295886634,
      },
      {
        regionId: 16,
        name: "Uzbekiston",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372733,
      },
      {
        regionId: 17,
        name: "Yozyowon",
        type: "district",
        neighborhood: [],
        region_osm_id: 244655950,
      },
      {
        regionId: 18,
        name: "Kokand",
        type: "city",
        neighborhood: [],
        region_osm_id: 922525016,
      },
      {
        regionId: 19,
        name: "Margilan",
        type: "city",
        neighborhood: [],
        region_osm_id: 27143436,
      },
    ]
  },
  {
    respublicId: 10,
    name: "Tashkent",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196251,
      coordinates: {
        lon: 69.3711365,
        lat: 41.0496815,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Akkurgan",
        type: "district",
        neighborhood: [],
        region_osm_id: 5750388,
      },
      {
        regionId: 2,
        name: "Chirchiq",
        type: "district",
        neighborhood: [],
        region_osm_id: 7723809,
      },
      {
        regionId: 3,
        name: "Ohangaron",
        type: "district",
        neighborhood: [],
        region_osm_id: 5745852,
      },
      {
        regionId: 4,
        name: "Yangiabod",
        type: "town",
        neighborhood: [],
        region_osm_id: 945415173,
      },
      {
        regionId: 5,
        name: "Angren",
        type: "city",
        neighborhood: [],
        region_osm_id: 245941430,
      },
      {
        regionId: 6,
        name: "Bekobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 5750396,
      },
      {
        regionId: 7,
        name: "Bostanlik",
        type: "district",
        neighborhood: [],
        region_osm_id: 2120216,
      },
      {
        regionId: 8,
        name: "Buka",
        type: "district",
        neighborhood: [],
        region_osm_id: 48359314,
      },
      {
        regionId: 9,
        name: "Zangiota",
        type: "district",
        neighborhood: [],
        region_osm_id: 4060435,
      },
      {
        regionId: 10,
        name: "Qibray",
        type: "district",
        neighborhood: [],
        region_osm_id: 5745803,
      },
      {
        regionId: 11,
        name: "Parkent",
        type: "district",
        neighborhood: [
          {
            id: '11-1',
            region_name: 'Qiziltog (Krasnogorsk)',
            type: 'qishloq'
          }
        ],
        region_osm_id: 5745823,
      },
      {
        regionId: 12,
        name: "Olmaliq",
        type: "town",
        neighborhood: [],
        region_osm_id: 10092921,
      },
      {
        regionId: 13,
        name: "Piskent",
        type: "district",
        neighborhood: [],
        region_osm_id: 5750391,
      },
      {
        regionId: 14,
        name: "Tashkent",
        type: "district",
        neighborhood: [],
        region_osm_id: 11071441,
      },
      {
        regionId: 15,
        name: "Nurafshan (Toytepa)",
        type: "town",
        neighborhood: [],
        region_osm_id: 47228710,
      },
      {
        regionId: 16,
        name: "Urtachirchik",
        type: "district",
        neighborhood: [],
        region_osm_id: 5748378,
      },
      {
        regionId: 17,
        name: "Chinaz",
        type: "district",
        neighborhood: [],
        region_osm_id: 5748414,
      },
      {
        regionId: 18,
        name: "Yukorichirchik",
        type: "district",
        neighborhood: [],
        region_osm_id: 5745839,
      },
      {
        regionId: 19,
        name: "Yangiiul",
        type: "town",
        neighborhood: [],
        region_osm_id: 7163853,
      },
      {
        regionId: 20,
        name: "Yangiyul",
        type: "district",
        neighborhood: [],
        region_osm_id: 5748407,
      },
      {
        regionId: 21,
        name: "Kuyichirchik",
        type: "district",
        neighborhood: [],
        region_osm_id: 5748465,
      },
    ]
  },
  {
    respublicId: 1,
    name: "Tashkentsh",
    type: "center",
    search_detail: {
      osmtype: 'R',
      osmid: 2216724,
      coordinates: {
        lon: 69.274291992,
        lat: 41.26954950,
        zoom: 11,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Chilanzar",
        type: "district",
        neighborhood: [],
        region_osm_id: 2441810,
      },
      {
        regionId: 2,
        name: "Uchtepa",
        type: "district",
        neighborhood: [],
        region_osm_id: 2434059,
      },
      {
        regionId: 3,
        name: "Olmazor",
        type: "district",
        neighborhood: [],
        region_osm_id: 2441651,
      },
      {
        regionId: 4,
        name: "Mirzo Ulugbek",
        type: "district",
        neighborhood: [],
        region_osm_id: 5620904,
      },
      {
        regionId: 5,
        name: "Yashnabad",
        type: "district",
        neighborhood: [],
        region_osm_id: 1751444,
      },
      {
        regionId: 6,
        name: "Mirabad",
        type: "district",
        neighborhood: [],
        region_osm_id: 2447634,
      },
      {
        regionId: 7,
        name: "Sirgali",
        type: "district",
        neighborhood: [],
        region_osm_id: 2447546,
      },
      {
        regionId: 8,
        name: "Yangi hayot",
        type: "district",
        neighborhood: [],
        region_osm_id: 12030887,
      },
      {
        regionId: 9,
        name: "Yunusabad",
        type: "district",
        neighborhood: [],
        region_osm_id: 2448072,
      },
      {
        regionId: 10,
        name: "Yakkasaray",
        type: "district",
        neighborhood: [],
        region_osm_id: 2443769,
      },
      {
        regionId: 11,
        name: "Shayhontohur",
        type: "district",
        neighborhood: [],
        region_osm_id: 2439529,
      },
      {
        regionId: 12,
        name: "Bektemir",
        type: "district",
        neighborhood: [],
        region_osm_id: 2447560,
      }
    ]
  },
  {
    respublicId: 20,
    name: "Sirdaryo",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196253,
      coordinates: {
        lon: 68.4341132,
        lat: 40.3737191,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Gulistan",
        type: "city",
        neighborhood: [],
        region_osm_id: 11086478,
      },
      {
        regionId: 2,
        name: "Sirdaryo",
        type: "district",
        neighborhood: [],
        region_osm_id: 11087876,
      },
      {
        regionId: 3,
        name: "Oqoltin",
        type: "district",
        neighborhood: [],
        region_osm_id: 11087238      ,
      },
      {
        regionId: 4,
        name: "Boyowut",
        type: "district",
        neighborhood: [],
        region_osm_id: 11086477,
      },
      {
        regionId: 5,
        name: "Guliston",
        type: "district",
        neighborhood: [
          {
            id: '5-1',
            region_name: 'ulugobod',
            type: 'shaxarchasi',
          },
          {
            id: '5-2',
            region_name: "Bahor",
            type: 'aholi-punkti',
          }
        ],
        region_osm_id: 11087519,
      },
      {
        regionId: 6,
        name: "Xovos",
        type: "district",
        neighborhood: [],
        region_osm_id: 11086994,
      },
      {
        regionId: 7,
        name: "Mirzaobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 11087046,
      },
      {
        regionId: 8,
        name: "Sardoba",
        type: "district",
        neighborhood: [],
        region_osm_id: 11087239,
      },
      {
        regionId: 9,
        name: "Sayxunobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 11087853,
      },
      {
        regionId: 10,
        name: "Yangiyer",
        type: "district",
        neighborhood: [],
        region_osm_id: 11086479,
      },
    ]
  },
  {
    respublicId: 25,
    name: "Jizzakh",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196254,
      coordinates: {
        lon: 67.4551198,
        lat: 40.3319095,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Jizzax",
        type: "city",
        neighborhood: [],
        region_osm_id: 173931100,
      },
      {
        regionId: 2,
        name: "Arnasay",
        type: "district",
        neighborhood: [],
        region_osm_id: 6990291,
      },
      {
        regionId: 3,
        name: "Baxmal",
        type: "district",
        neighborhood: [],
        region_osm_id: 7587151,
      },
      {
        regionId: 4,
        name: "Dustlik",
        type: "district",
        neighborhood: [],
        region_osm_id: 6990314,
      },
      {
        regionId: 5,
        name: "Forish",
        type: "district",
        neighborhood: [],
        region_osm_id: 7629998,
      },
      {
        regionId: 6,
        name: "Gallaorol",
        type: "district",
        neighborhood: [],
        region_osm_id: 7592938,
      },
      {
        regionId: 7,
        name: "Sharof Rashidov",
        type: "district",
        neighborhood: [],
        region_osm_id: 7593143,
      },
      {
        regionId: 8,
        name: "Mirzachul",
        type: "district",
        neighborhood: [],
        region_osm_id: 7626174,
      },
      {
        regionId: 9,
        name: "Pakhtakor",
        type: "district",
        neighborhood: [],
        region_osm_id: 7629494,
      },
      {
        regionId: 10,
        name: "Yangiabad",
        type: "district",
        neighborhood: [],
        region_osm_id: 7590755,
      },
      {
        regionId: 11,
        name: "Zaamin",
        type: "district",
        neighborhood: [],
        region_osm_id: 7587152,
      },
      {
        regionId: 12,
        name: "Zarbdar",
        type: "district",
        neighborhood: [],
        region_osm_id: 7591363,
      },
      {
        regionId: 13,
        name: "Zafarobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 6990287,
      },
    ]
  },
  {
    respublicId: 30,
    name: "Samarqand",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196249,
      coordinates: {
        lon: 66.1282889,
        lat: 39.7337023,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Samarqand",
        type: "city",
        neighborhood: [],
        region_osm_id: 245542318,
      },
      {
        regionId: 2,
        name: "Bulung`ur",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372728,
      },
      {
        regionId: 3,
        name: "Ishtixon",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372676,
      },
      {
        regionId: 4,
        name: "Jomboy",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372809,
      },
      {
        regionId: 5,
        name: "Qo‘shrabot",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372760,
      },
      {
        regionId: 6,
        name: "Kattaqo‘rg‘on",
        type: "district",
        neighborhood: [
          {
            id: '6-1',
            region_name: "ingichka",
            type: 'qishloq',
          }
        ],
        region_osm_id: 309372796,
      },
      {
        regionId: 7,
        name: "Narpay",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372833,
      },
      {
        regionId: 8,
        name: "Nurobod",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372666,
      },
      {
        regionId: 9,
        name: "Oqdaryo",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372723,
      },
      {
        regionId: 10,
        name: "Paxtachi",
        type: "district",
        neighborhood: [],
        region_osm_id: 12474376,
      },
      {
        regionId: 11,
        name: "Payariq",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372820,
      },
      {
        regionId: 12,
        name: "Pastdarg‘om",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372667,
      },
      {
        regionId: 13,
        name: "Samarqand",
        type: "district",
        neighborhood: [
          {
            "id": '13-1',
            "region_name": "xishrav",
            "type": 'qishloq',
          },
          {
            "id": '13-2',
            "region_name": "farxod",
            "type": 'qishloq',
          },
          {
            "id": '13-3',
            "region_name": "kimyogarlar",
            "type": 'qishloq',
          }
        ],
        region_osm_id: 309372795,
      },
      {
        regionId: 14,
        name: "Toyloq",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372740,
      },
      {
        regionId: 15,
        name: "Urgut",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372827,
      },
      {
        regionId: 16,
        name: "Kattaqo‘rg‘on",
        type: "city",
        neighborhood: [],
        region_osm_id: 309372796,
      },
    ]
  },
  {
    respublicId: 85,
    name: "Navoiy",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196246,
      coordinates: {
        lon: 64,
        lat: 42,
        zoom: 7,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Navoiy",
        type: "city",
        neighborhood: [],
        region_osm_id: 110282097,
      },
      {
        regionId: 2,
        name: "Kanimekh",
        type: "district",
        neighborhood: [],
        region_osm_id: 2186085,
      },
      {
        regionId: 3,
        name: "Karmana",
        type: "district",
        neighborhood: [],
        region_osm_id: 11158845,
      },
      {
        regionId: 4,
        name: "Qiziltepa",
        type: "district",
        neighborhood: [],
        region_osm_id: 11158844,
      },
      {
        regionId: 5,
        name: "Xatirchi",
        type: "district",
        neighborhood: [],
        region_osm_id: 11158813,
      },
      {
        regionId: 6,
        name: "Navbahor",
        type: "district",
        neighborhood: [],
        region_osm_id: 11157435,
      },
      {
        regionId: 7,
        name: "Nurota",
        type: "district",
        neighborhood: [],
        region_osm_id: 11158818,
      },
      {
        regionId: 8,
        name: "Tamdy",
        type: "district",
        neighborhood: [],
        region_osm_id: 2186086,
      },
      {
        regionId: 9,
        name: "Uchkuduk",
        type: "district",
        neighborhood: [],
        region_osm_id: 2186087,
      },
      {
        regionId: 10,
        name: "Zarafshan",
        type: "city",
        neighborhood: [],
        region_osm_id: 195846326,
      },
    ]
  },
  {
    respublicId: 80,
    name: "Bukhara",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 1670973,
      coordinates: {
        lon: 63.5470584,
        lat: 40.229366,
        zoom: 7,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Bukhara",
        type: "city",
        neighborhood: [],
        region_osm_id: 13070474,
      },
      {
        regionId: 2,
        name: "Olot",
        type: "district",
        neighborhood: [],
        region_osm_id: 11178494,
      },
      {
        regionId: 3,
        name: "Galaosiyo",
        type: "city",
        neighborhood: [],
        region_osm_id: 45589946,
      },
      {
        regionId: 4,
        name: "Gijduvan",
        type: "town",
        neighborhood: [],
        region_osm_id: 176098986,
      },
      {
        regionId: 5,
        name: "Jondor",
        type: "district",
        neighborhood: [],
        region_osm_id: 3587820005,
      },
      {
        regionId: 6,
        name: "Kogon",
        type: "district",
        neighborhood: [],
        region_osm_id: 11177967,
      },
      {
        regionId: 7,
        name: "Qorako’l",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372672,
      },
      {
        regionId: 8,
        name: "Qorovulbozor",
        type: "district",
        neighborhood: [],
        region_osm_id: 11159957,
      },
      {
        regionId: 9,
        name: "Peshku",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372665,
      },
      {
        regionId: 10,
        name: "Romiton",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372714,
      },
      {
        regionId: 11,
        name: "Shofirkon",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372901,
      },
      {
        regionId: 12,
        name: "Vobkent",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372692,
      },
      {
        regionId: 13,
        name: "Bukhoro",
        type: "district",
        neighborhood: [],
        region_osm_id: 11180733,
      },
    ]
  },
  {
    respublicId: 90,
    name: "Xorazm",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196242,
      coordinates: {
        lon: 61.1636,
        lat: 41.2902835,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Urgench",
        type: "city",
        neighborhood: [],
        region_osm_id: 110132970,
      },
      {
        regionId: 2,
        name: "Khiva",
        type: "town",
        neighborhood: [],
        region_osm_id: 110260748,
      },
      {
        regionId: 3,
        name: "Bagat",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097711,
      },
      {
        regionId: 4,
        name: "Gurlen",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097623,
      },
      {
        regionId: 5,
        name: "Koshkupyr",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097689,
      },
      {
        regionId: 6,
        name: "Urgench",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097690,
      },
      {
        regionId: 7,
        name: "Hazorasp",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097814,
      },
      {
        regionId: 8,
        name: "Khanka",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097712,
      },
      {
        regionId: 9,
        name: "Khiva",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097691,
      },
      {
        regionId: 10,
        name: "Shavat",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097624,
      },
      {
        regionId: 11,
        name: "Yangiariq",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097692,
      },
      {
        regionId: 12,
        name: "Yangibozor",
        type: "district",
        neighborhood: [],
        region_osm_id: 2097625,
      },
      {
        regionId: 13,
        name: "Pitnak",
        type: "town",
        neighborhood: [],
        region_osm_id: 394570342,
      },
      {
        regionId: 14,
        name: "Tuproqqalʼa",
        type: "county",
        neighborhood: [],
        region_osm_id: 11992833,
      },
    ]
  },
  {
    respublicId: 95,
    name: "Karakalpakstan",
    type: "respublic",
    search_detail: {
      osmtype: 'R',
      osmid: 196241,
      coordinates: {
        lon: 57.6234617,
        lat: 43.7738841,
        zoom: 7,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Nókis",
        type: "city",
        neighborhood: [],
        region_osm_id: 7284011,
      },
      {
        regionId: 2,
        name: "Ámiwdárya",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095807,
      },
      {
        regionId: 3,
        name: "Beruniy",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095997,
      },
      {
        regionId: 4,
        name: "Bozatau'",
        type: "district",
        neighborhood: [],
        region_osm_id: 10041797,
      },
      {
        regionId: 5,
        name: "Qanlıkól",
        type: "district",
        neighborhood: [],
        region_osm_id: 2094502,
      },
      {
        regionId: 6,
        name: "Qaraózek",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095797,
      },
      {
        regionId: 7,
        name: "Kegeyli",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095788,
      },
      {
        regionId: 8,
        name: "Qońırat",
        type: "district",
        neighborhood: [],
        region_osm_id: 2094349,
      },
      {
        regionId: 9,
        name: "Muynoq",
        type: "district",
        neighborhood: [],
        region_osm_id: 2094483,
      },
      {
        regionId: 10,
        name: "Nókis",
        type: "district",
        neighborhood: [],
        region_osm_id: 7284021,
      },
      {
        regionId: 11,
        name: "Taqıyatas",
        type: "district",
        neighborhood: [],
        region_osm_id: 7505068,
      },
      {
        regionId: 12,
        name: "Taxtakopir",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095849,
      },
      {
        regionId: 13,
        name: "Tórtkúl",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095998,
      },
      {
        regionId: 14,
        name: "Xojeli",
        type: "district",
        neighborhood: [],
        region_osm_id: 2094524,
      },
      {
        regionId: 15,
        name: "Chimbay",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095789,
      },
      {
        regionId: 16,
        name: "Shomanay",
        type: "district",
        neighborhood: [],
        region_osm_id: 2094497,
      },
      {
        regionId: 17,
        name: "Ellikqala",
        type: "district",
        neighborhood: [],
        region_osm_id: 2095999,
      },
    ]
  },
  {
    respublicId: 70,
    name: "Qashqadaryo",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 1670974,
      coordinates: {
        lon: 66.192626,
        lat: 38.5639397,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Qarshi",
        type: "city",
        neighborhood: [
          {
            "id": '1-1',
            "region_name": "sheyxali",
            "type": 'qishloq',
          }
        ],
        region_osm_id: 228236278,
      },
      {
        regionId: 2,
        name: "Qarshi",
        type: "district",
        neighborhood: [],
        region_osm_id: 13618732,
      },
      {
        regionId: 3,
        name: "Chirakchi",
        type: "district",
        neighborhood: [],
        region_osm_id: 13342290,
      },
      {
        regionId: 4,
        name: "Dehqonobod",// check again
        type: "district",
        neighborhood: [],
        region_osm_id: 309372773,
      },
      {
        regionId: 5,
        name: "G’uzor",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372773,
      },
      {
        regionId: 6,
        name: "Kamashi",
        type: "district",
        neighborhood: [],
        region_osm_id: 9037690,
      },
      {
        regionId: 7,
        name: "Koson",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372747,
      },
      {
        regionId: 8,
        name: "Kasbi",
        type: "district",
        neighborhood: [],
        region_osm_id: 11856183,
      },
      {
        regionId: 9,
        name: "Kitob",
        type: "district",
        neighborhood: [],
        region_osm_id: 8655517,
      },
      {
        regionId: 10,
        name: "Mirishkor",
        type: "district",
        neighborhood: [],
        region_osm_id: 11857775,
      },
      {
        regionId: 11,
        name: "Muborak",
        type: "district",
        neighborhood: [],
        region_osm_id: 309372767,
      },
      {
        regionId: 12,
        name: "Nishon",
        type: "district",
        neighborhood: [],
        region_osm_id: 10764730,
      },
      {
        regionId: 13,
        name: "Shakhrisabz",
        type: "district",
        neighborhood: [],
        region_osm_id: 8660162,
      },
      {
        regionId: 14,
        name: "Yakkabog",
        type: "district",
        neighborhood: [],
        region_osm_id: 8827580,
      },
      {
        regionId: 15,
        name: "Shahrisabz",
        type: "city",
        neighborhood: [],
        region_osm_id: 309372759,
      },
    ]
  },
  {
    respublicId: 75,
    name: "Surxondaryo",
    type: "region",
    search_detail: {
      osmtype: 'R',
      osmid: 196248,
      coordinates: {
        lon: 67.510986,
        lat: 37.9520843,
        zoom: 9,
      },
    },
    regions: [
      {
        regionId: 1,
        name: "Termez",
        type: "city",
        neighborhood: [],
        region_osm_id: 245557356,
      },
      {
        regionId: 2,
        name: "Kumkurghon",
        type: "district",
        neighborhood: [],
        region_osm_id: 11123658,
      },
      {
        regionId: 3,
        name: "Termiz",
        type: "district",
        neighborhood: [],
        region_osm_id: 11137520,
      },
      {
        regionId: 4,
        name: "Denov",
        type: "district",
        neighborhood: [],
        region_osm_id: 11180683,
      },
      {
        regionId: 5,
        name: "Uzun",
        type: "district",
        neighborhood: [],
        region_osm_id: 11180857,
      },
      {
        regionId: 6,
        name: "Sariosiyo",
        type: "district",
        neighborhood: [],
        region_osm_id: 11114152,
      },
      {
        regionId: 7,
        name: "Boysun",
        type: "district",
        neighborhood: [],
        region_osm_id: 11114153,
      },
      {
        regionId: 8,
        name: "Sherabad",
        type: "district",
        neighborhood: [],
        region_osm_id: 11184260,
      },
      {
        regionId: 9,
        name: "Shurchi",
        type: "district",
        neighborhood: [],
        region_osm_id: 11180731,
      },
      {
        regionId: 10,
        name: "Angor",
        type: "district",
        neighborhood: [],
        region_osm_id: 11184154,
      },
      {
        regionId: 11,
        name: "Jarkurgan",
        type: "district",
        neighborhood: [],
        region_osm_id: 11184121,
      },
      {
        regionId: 12,
        name: "Muzrabot",
        type: "district",
        neighborhood: [],
        region_osm_id: 11184259,
      },
      {
        regionId: 13,
        name: "Kizirik",
        type: "district",
        neighborhood: [],
        region_osm_id: 11184007,
      },
      {
        regionId: 14,
        name: "Bandikhon",
        type: "district",
        neighborhood: [],
        region_osm_id: 11183885,
      },
      {
        regionId: 15,
        name: "Oltinsoy",
        type: "district",
        neighborhood: [],
        region_osm_id: 11149913,
      },
    ]
  },
]
